runs:
  - name: finetune_mace_oc22_head_full
    backend: mace
    task: finetune
    run_dir: /home/kjt/projects/RL-reaction-path/runs/finetune_tests/mace_oc22_head_full
    model_in: /home/kjt/projects/RL-reaction-path/runs/finetune_tests/mace_oc22_head_smoke/init_backbone.pt
    data:
      format: lmdb
      train: /home/kjt/projects/RL-reaction-path/Data/oc22_data/oc22_data/s2ef-total/train
      val: /home/kjt/projects/RL-reaction-path/Data/oc22_data/oc22_data/s2ef-total/val_id
    train:
      input_json: /home/kjt/projects/RL-reaction-path/models/MACE-MH-1/OC22/model.json
      head_key: oc22
      freeze: head_only
      epochs: 5
      batch_size: 4
      accum_steps: 8
      num_workers: 4
      lr: 1.0e-4
      weight_decay: 0.0
      optimizer: adamw
      amp: true
      progress_bar: true
      progress_mininterval: 0.5
      log_every: 200
      save_every: 1
